version: '3.8'
services:
  db:
    container_name: database
    image: postgres:latest
    env_file: 
      - .env.dev
    expose:
      - 5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./docker/database:/var/lib/postgresql/data
  app:
    container_name: app
    build: ./case
    env_file:
      - .env.dev
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - ./docker/static:/app/static
    